#!/bin/bash

# Temporary script to setup execution environment to execute
# bpfd from anywhere in the system once this is sourced.
# I source it from .bashrc. Once we have proper libbpf
# installation or its statically linked, this wont be needed.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Could get rid of this once libbpf is compiled into
# the binary statically.
export LD_LIBRARY_PATH="$DIR"

export PATH="$PATH:$DIR"
